vim.g.python3_host_prog = '~/.pyenv/versions/neovim3/bin/python'
require('plugins')
require('file-explorer')
require('options')
require('styling')
require('mappings')
require('syntax-highlight')
require('statusbar')
require('fuzzy-finder')
require('mason-config')
require('lsp')
require('code-completion')
require('debugger')
require('hoverdoc')
require('git')
require('terminal')
require('autopairs')
